version: '3.8'

services:
  app:
    build:
      context: ./avito_test
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./avito_test/:/avito_test/
    ports:
      - 8000:8000
    env_file:
      - avito_test/.env.dev
    restart: always

  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data


volumes:
  my_dbdata: